-- Estrutura inicial para um NOVO projeto Supabase vazio.
-- Baseada nos campos do aplicativo; nao e um backup do banco da imagem.
-- Execute o arquivo inteiro no SQL Editor. Nenhum dado e importado.
-- As tabelas privadas ficam bloqueadas pela RLS ate configurar autenticacao
-- e politicas. O login por nome/documento do catalogo nao e Supabase Auth.
-- Nao execute create_orcamentos.sql depois: ele libera acesso anonimo.
-- A view abaixo e uma proposta: a definicao original nao foi fornecida.
-- Nao cria automacoes de estoque/aceitacao: o aplicativo ja altera estoque.

begin;

create table public.cadastro (
  id bigint generated by default as identity primary key,
  "id-client" text unique,
  cliente text not null,
  telefone text,
  "identificação" text,
  nome_fantasia text,
  endereco text,
  cep text,
  numero text,
  complemento text,
  bairro text,
  municipio text,
  lista_negra boolean not null default false,
  motivo text,
  created_at timestamptz not null default now()
);

create table public.blacklist (
  id bigint generated by default as identity primary key,
  cliente_id bigint references public.cadastro(id) on delete restrict,
  documento text not null,
  motivo text,
  created_at timestamptz not null default now()
);

create table public.estoque (
  id uuid primary key default gen_random_uuid(),
  codigo_interno text unique,
  item text not null unique,
  disponivel integer not null default 0 check (disponivel >= 0),
  reservado integer not null default 0 check (reservado >= 0),
  alugado integer not null default 0 check (alugado >= 0),
  preco numeric(12,2) not null default 0 check (preco >= 0),
  created_at timestamptz not null default now()
);

create table public.reservas (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.cadastro(id) on delete restrict,
  item text not null,
  codigo_item text,
  quantidade integer not null check (quantidade > 0),
  data_evento date not null,
  data_festa date,
  data_devolucao date not null,
  status text not null default 'Pendente',
  forma_pagamento text default 'Não Informado',
  valor_total numeric(12,2) not null default 0,
  taxa_entrega numeric(12,2) not null default 0,
  desconto numeric(12,2) not null default 0,
  observacoes text,
  endereco_secundario text,
  municipio_secundario text,
  bairro_secundario text,
  numero_secundario text,
  complemento_secundario text,
  created_at timestamptz not null default now(),
  check (data_devolucao >= data_evento)
);

-- Tabela legada consultada pelo aplicativo; novas reservas usam reservas.
create table public.reservas_futuras (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.cadastro(id) on delete restrict,
  item text not null,
  codigo_item text,
  quantidade integer not null check (quantidade > 0),
  data_evento date not null,
  data_festa date,
  data_devolucao date not null,
  status text not null default 'Pendente',
  forma_pagamento text default 'Não Informado',
  valor_total numeric(12,2) not null default 0,
  taxa_entrega numeric(12,2) not null default 0,
  desconto numeric(12,2) not null default 0,
  observacoes text,
  endereco_secundario text,
  municipio_secundario text,
  bairro_secundario text,
  numero_secundario text,
  complemento_secundario text,
  created_at timestamptz not null default now(),
  check (data_devolucao >= data_evento)
);

create table public.movimentacao_caixa (
  id bigint generated by default as identity primary key,
  cliente_id bigint references public.cadastro(id) on delete restrict,
  descricao text not null,
  valor numeric(12,2) not null,
  tipo text not null check (tipo in ('Receita', 'Despesa')),
  categoria text,
  data timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table public.orcamentos (
  id bigint generated by default as identity primary key,
  cliente_id bigint references public.cadastro(id) on delete restrict,
  cliente_nome text not null,
  data_reserva date not null,
  data_evento date not null,
  data_retirada date not null,
  valor_total numeric(12,2) not null default 0,
  taxa_entrega numeric(12,2) not null default 0,
  desconto numeric(12,2) not null default 0,
  adiantamento numeric(12,2) not null default 0,
  saldo_restante numeric(12,2) not null default 0,
  observacoes text,
  status text not null default 'Aberto',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orcamento_itens (
  id bigint generated by default as identity primary key,
  orcamento_id bigint not null references public.orcamentos(id) on delete cascade,
  estoque_id uuid references public.estoque(id) on delete set null,
  item text not null,
  codigo_item text,
  quantidade integer not null default 1 check (quantidade > 0),
  valor_unitario numeric(12,2) not null default 0,
  valor_total numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table public.pedidos_online (
  id bigint generated by default as identity primary key,
  cliente_nome text not null,
  -- O catalogo envia a identificacao/documento neste campo, apesar do nome.
  cliente_whatsapp text not null,
  itens_texto text not null,
  data_reserva date not null,
  data_devolucao date not null,
  status text not null default 'Pendente',
  created_at timestamptz not null default now(),
  check (data_devolucao >= data_reserva)
);

create view public.gestao_pedidos_online
with (security_invoker = true) as
select id, cliente_nome, cliente_whatsapp, itens_texto,
       data_reserva, data_devolucao, status, created_at
from public.pedidos_online;

create index on public.blacklist(cliente_id);
create index on public.blacklist(documento);
create index on public.reservas(cliente_id, data_evento);
create index on public.reservas(data_evento, data_devolucao);
create index on public.reservas_futuras(cliente_id, data_evento);
create index on public.movimentacao_caixa(cliente_id);
create index on public.movimentacao_caixa(data);
create index on public.orcamentos(cliente_id);
create index on public.orcamentos(data_reserva);
create index on public.orcamento_itens(orcamento_id);
create index on public.orcamento_itens(estoque_id);
create index on public.pedidos_online(created_at);

create function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_orcamentos_updated_at
before update on public.orcamentos
for each row execute function public.set_updated_at();

alter table public.cadastro enable row level security;
alter table public.blacklist enable row level security;
alter table public.estoque enable row level security;
alter table public.reservas enable row level security;
alter table public.reservas_futuras enable row level security;
alter table public.movimentacao_caixa enable row level security;
alter table public.orcamentos enable row level security;
alter table public.orcamento_itens enable row level security;
alter table public.pedidos_online enable row level security;

-- Sem politicas, as tabelas privadas nao ficam acessiveis pelo navegador.
revoke all on public.cadastro, public.blacklist, public.estoque,
  public.reservas, public.reservas_futuras, public.movimentacao_caixa,
  public.orcamentos, public.orcamento_itens, public.pedidos_online,
  public.gestao_pedidos_online from anon, authenticated;

-- Acesso de backend; nunca coloque a chave service_role no frontend.
grant usage on schema public to service_role;
grant all on public.cadastro, public.blacklist, public.estoque,
  public.reservas, public.reservas_futuras, public.movimentacao_caixa,
  public.orcamentos, public.orcamento_itens, public.pedidos_online,
  public.gestao_pedidos_online to service_role;
grant usage, select on sequence public.cadastro_id_seq,
  public.blacklist_id_seq, public.reservas_id_seq,
  public.reservas_futuras_id_seq, public.movimentacao_caixa_id_seq,
  public.orcamentos_id_seq, public.orcamento_itens_id_seq,
  public.pedidos_online_id_seq to service_role;

notify pgrst, 'reload schema';
commit;
